baseURL: ""
languageCode: 'en-us'
title: "Vent & Write"
theme: PaperMod

params:
  homeInfoParams:
    Title: Hello there!
    Content: "This will be a \"little corner\" of the web where I will archive some of my notes and thoughts. \n\n My name is Matteo, I'm a master student of **Computer Ingeneering** into the University Of Salento (Italy, Apulia). \n\n I like the thought that I can write and keeping track all the things that I learn/do in computer science, society, interpersonal relationships, and more I guess. So: **NO topic, I just write my things**."

  socialIcons:
    - name: GitHub
      url: "https://github.com/lonelygunter"
    - name: GitLab
      url: "https://gitlab.com/lonelygunter"

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 4